@echo off
echo Restarting backend server...
cd backend
echo Stopping any existing Python processes...
taskkill /F /IM python.exe 2>nul
timeout /t 2
echo Starting backend server...
start cmd /k "python main.py"
echo Backend server started. Opening debug page...
timeout /t 3
start http://localhost:3000/debug-coach
echo Done!
